#!/bin/sh

set -e

if [ ! -c $PLATFORMIO_UPLOAD_PORT ]
then
  export PLATFORMIO_UPLOAD_PORT=$(ioreg -l | awk -F\" '/IOCalloutDevice.*usbserial/ {P=$4}; END{print P}')
fi


E=mesmerizer

#~/.platformio/penv/bin/pio run  -e $E
#~/.platformio/penv/bin/pio run --target buildfs -e $E

pio run    --target upload -e $E
# pio device monitor -e mesmerizer
tio -a latest
# (stty 115200 ; cat -u) < $PLATFORMIO_UPLOAD_PORT
